#!/usr/bin/env sh

set -e

DEBUG_MODE=

if [ "$1" = "debug" ]; then
    DEBUG_MODE=debug
fi

cd com.cdsoftware.lirion.attendance.targetplatform
./plugin-builder $DEBUG_MODE ../com.cdsoftware.lirion.attendance ../com.cdsoftware.lirion.attendance.test
